END/CRUD/models.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

class Usuario(db.Model):
    __tablename__ = 'usuario'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nome = db.Column(db.String(100))
    email = db.Column(db.String(100))
    senha = db.Column(db.String(100))

    def __repr__(self):
        return '<Usuario %r>' % self.nome

class LivroCadastrado(db.Model):
    __tablename__ = 'livro'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    titulo = db.Column(db.String(100))
    autor = db.Column(db.String(100))
    genero = db.Column(db.String(100))
    avaliacao_media = db.Column(db.Float)


class LivroLido(db.Model):
    __tablename__ = 'livrolido'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    usuario_id = db.Column(db.Integer, db.ForeignKey('usuario.id'))
    livro_cadastrado = db.Column(db.Integer, db.ForeignKey('livro.id'))
    data_leitura = db.Column(db.Date)
    avaliação = db.Column(db.Integer)

    def __repr__(self):
        return '<Livro %r>' % self.titulo   

END/CRUD/app.py
from flask import Flask, render_template, request, redirect, url_for
from flask import jsonify
from flask_sqlalchemy import SQLAlchemy
from routes import book
from models import db, Usuario, LivroCadastrado, LivroLido

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
db.init_app(app)

with app.app_context():
    db.create_all()

app.register_blueprint(book)

if __name__ == '__main__':
    app.run(debug=True)

END/CRUD/controllers.py
from models import db, LivroCadastrado

class Controller:
    def book_add(data):
        newBook = LivroCadastrado(titulo= data["titulo"], autor= data["autor"], genero= data["genero"], avaliacao_media= float(data["avaliacao_media"]))
        db.session.add(newBook)
        db.session.commit()


    def book_list():
        books = LivroCadastrado.query.all()
        return books
    
    def book_find(id):
        return LivroCadastrado.query.get(id)

    def book_update(id, data):
        book = LivroCadastrado.query.get(id)
        book.titulo = data["titulo"]
        book.autor = data["autor"]
        book.genero = data["genero"]
        book.avaliacao_media = float(data["avaliacao_media"])
        db.session.commit()
        return book
    
    def book_delete(id):
        book = LivroCadastrado.query.get(id)
        db.session.delete(book)
        db.session.commit()

END/CRUD/routes.py
from flask import Flask, render_template, request, redirect, url_for, jsonify, Blueprint
from models import Usuario, LivroCadastrado, LivroLido
from controllers import Controller


book = Blueprint('book', __name__)
@book.route("/", methods=["GET"])
def main():
    return render_template("index.html")

@book.route("/add", methods=["GET", "POST"])
def book_add():
    if request.method == 'POST':
        data = request.form.to_dict()
        Controller.book_add(data)
        return redirect(url_for('book.main'))
    return render_template("add.html")

@book.route("/home", methods=["GET"])
def book_list():
    books = Controller.book_list()
    return render_template("home.html", books=books)

@book.route("/edit/<int:id>", methods=["GET", "POST"])
def book_edit(id):
    if request.method == 'GET':
        book = Controller.book_find(id)
        return render_template("edit.html", book=book)
    data = request.form.to_dict()
    Controller.book_update(id, data)
    return redirect(url_for('book.book_list'))

@book.route("/delete/<int:id>", methods=["GET"])
def book_delete(id):
    Controller.book_delete(id)
    return redirect(url_for('book.book_list'))

END/CRUD/templates/add.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
<h1>Adicione um Livro</h1>
<form method="POST" action="{{ url_for('book.book_add') }}" style="position: relative;">
        <div class="InputDiv">
            <input type="text" id="titleInput" name="titulo" placeholder="Insira o título do livro" required>
            <input type="text" id="authorInput" name="autor" placeholder="Autor do livro" required>
            <input type="text" id="genreInput" name="genero" placeholder="Gênero do livro" required>
            <input type="number" id="ratingInput" name="avaliacao_media" placeholder="Avaliação Média (0-10)" step="0.1" min="0" max="10" required>
            <button type="submit">Cadastrar Livro</button>
        </div>
</form>
<script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}

END/CRUD/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookLog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <span class="logo">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo do BookAdder">
            <p>BookLog</p>
        </span>
        <span id="homeButton">
            <a href="{{ url_for('book.book_list') }}">Home</a></span>
    </header>
    <main>

        {% block content %}{% endblock %}

    </main>
</body>
</html>

END/CRUD/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
<h1>Edite o Livro</h1>
<form method="POST" action="{{ url_for('book.book_edit',id=book.id) }}">
    <div class="InputDiv">
        <input type="text" id="titleInput" name="titulo" value="{{ book.titulo }}" placeholder="Insira o título do livro" required>
        <input type="text" id="authorInput" name="autor" value="{{ book.autor }}" placeholder="Autor do livro" required>
        <input type="text" id="genreInput" name="genero" value="{{ book.genero }}" placeholder="Gênero do livro" required>
        <input type="number" id="ratingInput" name="avaliacao_media" value="{{ book.avaliacao_media }}" placeholder="Avaliação Média (0-10)" step="0.1" min="0" max="10" required>
        <button type="submit">Atualizar Livro</button>
    </div>
</form>
<script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}

END/CRUD/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <h1>Livros Cadastrados</h1>
    <div class="books-container">
        {% if books %}
            <ul class="books-list">
                {% for book in books %}
                    <li class="book-item">
                        <h2>{{ book.titulo }}</h2>
                        <p><strong>Autor:</strong> {{ book.autor }}</p>
                        <p><strong>Gênero:</strong> {{ book.genero }}</p>
                        <p><strong>Avaliação Média:</strong> {{ book.avaliacao_media }}</p>
                        <div class="book-actions">
                            <a href="{{url_for('book.book_edit', id=book.id)}}" class="btn btn-edit">Editar</a>
                            <a href="{{url_for('book.book_delete', id=book.id)}}" class="btn btn-delete">Deletar</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nenhum livro cadastrado.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

END/CRUD/templates/index.html
    {% extends 'base.html' %}

    {% block content %}
    <main>
        <button id="addBookButton">
        <a href="/add">+</a></button>
        <p id="addBookText">Adicione um livro</p>
    </main>
    {% endblock %}